// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzLqyZorBfMqDtb5EdYoFveeFskaVWpek',
    appId: '1:198241456872:web:992fe673ea6670c0dc2f5d',
    messagingSenderId: '198241456872',
    projectId: 'studentapp-cb4eb',
    authDomain: 'studentapp-cb4eb.firebaseapp.com',
    storageBucket: 'studentapp-cb4eb.firebasestorage.app',
    measurementId: 'G-MEMYRCM6Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcUIIAx0ymIGqRMj2wHavMFpEHHDEnuhA',
    appId: '1:198241456872:android:3cf005f2b9f06fd5dc2f5d',
    messagingSenderId: '198241456872',
    projectId: 'studentapp-cb4eb',
    storageBucket: 'studentapp-cb4eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKwqGMgUldJQcKjgmNkxkxDVy_xqY1IRU',
    appId: '1:198241456872:ios:3592c71120834e90dc2f5d',
    messagingSenderId: '198241456872',
    projectId: 'studentapp-cb4eb',
    storageBucket: 'studentapp-cb4eb.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKwqGMgUldJQcKjgmNkxkxDVy_xqY1IRU',
    appId: '1:198241456872:ios:3592c71120834e90dc2f5d',
    messagingSenderId: '198241456872',
    projectId: 'studentapp-cb4eb',
    storageBucket: 'studentapp-cb4eb.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzLqyZorBfMqDtb5EdYoFveeFskaVWpek',
    appId: '1:198241456872:web:f2091e80e05abe5fdc2f5d',
    messagingSenderId: '198241456872',
    projectId: 'studentapp-cb4eb',
    authDomain: 'studentapp-cb4eb.firebaseapp.com',
    storageBucket: 'studentapp-cb4eb.firebasestorage.app',
    measurementId: 'G-N8PHBSHDJK',
  );
}
